apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eventhub-viewer
  labels:
    app: eventhub-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventhub-viewer
  template:
    metadata:
      labels:
        app: eventhub-viewer
    spec:
      containers:
      - name: eventhub-viewer
        image: shkreza/eventhub-viewer:v0.27
        ports:
        - name: port-443
          containerPort: 443
        resources:
          limits:
            cpu: 0.2
            memory: "80Mi"
        volumeMounts:
        - name: tls-secrets
          mountPath: /secrets/tls-secrets
          readOnly: true
      volumes:
      - name: tls-secrets
        secret:
          secretName: tls-secrets
