kind: Service
apiVersion: v1
metadata:
    name: eventhub-viewer
spec:
    selector:
        app: eventhub-viewer
    ports:
      - protocol: TCP
        port: 443
        targetPort: 443
    type:
        LoadBalancer
